# Generated by Django 5.2.4 on 2025-08-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=60)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
