# Generated by Django 5.2.4 on 2025-08-03 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('unidad', models.CharField(max_length=5)),
                ('existencia', models.IntegerField()),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_compra_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoMovimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_inventario', to=settings.AUTH_USER_MODEL)),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.tipomovimiento')),
            ],
        ),
        migrations.CreateModel(
            name='detalleInventario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventory.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_inventario', to='inventory.producto')),
            ],
        ),
    ]
