# Generated by Django 5.2.4 on 2025-08-10 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
