# Generated by Django 5.2.4 on 2025-08-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_carrito', to='customers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='detalleCarrito',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='orders.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_carrito', to='inventory.producto')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(verbose_name=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pedidos', to='customers.cliente')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_pedido', to='billing.factura')),
            ],
        ),
    ]
